name: storage_capacity
description: A package facilitates the use of storage capacity. Taking free space, occupied space, total space and device capacity.
version: 0.0.2
homepage: https://komus.io/
repository: https://github.com/davi19/storage_capacity

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.komus.storage_capacity
        pluginClass: StorageCapacityPlugin
      ios:
        pluginClass: StorageCapacityPlugin

